# Generated by Django 4.2.3 on 2024-05-10 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bike',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
