# Generated by Django 4.2.3 on 2023-07-14 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import other_functionalities.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(validators=[other_functionalities.validators.MinRequirementChars(min_string_length=2, validator_message='The message is too short.')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='sender')),
            ],
        ),
    ]
