# Generated by Django 4.2.3 on 2023-07-14 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.country', verbose_name='country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('postCode', models.CharField(blank=True, max_length=10, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.country', verbose_name='country')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.region', verbose_name='region')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=60, null=True)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.city', verbose_name='city')),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.country', verbose_name='country')),
                ('region_id', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='address.region', verbose_name='region')),
            ],
        ),
    ]
